from random import randint
A_random = input("Enter the lower limit of range.")
B_random = input("Enter the upper limit of range.")
while len(str(A_random))==0 or len(str(B_random))==0 or not A_random.isnumeric() or not B_random.isnumeric():
    if len(A_random)==0:
        print("Invalid input... try again.")
        A_random = int(input("Enter the lower limit of range."))
        continue
    elif len(B_random)==0:
        print("Invalid input... try again.")
        B_random = int(input("Enter the upper limit of range."))
        continue
    elif not A_random.isnumeric():
        print("Enter a number not letters... Try again")
        A_random = input("Enter the lower limit of range.")
        continue
    elif not B_random.isnumeric():
        print("Enter a number not letters... Try again")
        B_random = input("Enter the upper limit of range.")
        continue
numb_generated = randint(int(A_random), int(B_random))

class Game:
    def __init__(self,Name):
        print("Welcome to the Guess the number challenge...\nThis game has two players. You need to guess the random number generated by the system. The random number would be in the range given by the user. ")
        self.choice = 0
        self.trials = 0
        self.name = Name
    def Ask_Input(self):
        print(f"{self.name}:)")
        Numb_Choice = input("Enter your  guess-")
        if len(Numb_Choice)==0 or int(Numb_Choice)>int(B_random) or int(Numb_Choice)<int(A_random):
            print("Invalid Input try again.")
            self.trials -= 1
            self.Ask_Input()
        else:
            self.choice = int(Numb_Choice)
            self.Checking_Choice()
        return '\n'.join([])
    def Checking_Choice(self):
        if self.choice == numb_generated:
            self.trials += 1
            print(self.Guess_Correct())
            return '\n'.join([])
        elif self.choice > numb_generated:
            print(self.Guess_Wrong_Greater())
            self.trials += 1
            self.Ask_Input()
            return '\n'.join([])
        elif self.choice < numb_generated:
            print(self.Guess_Wrong_Lesser())
            self.trials += 1
            self.Ask_Input()
            return '\n'.join([])

    def Guess_Correct(self):
        print(self.trials)
        return f"\nYou guessed the correct number in {self.trials} trials"

    def Guess_Wrong_Greater(self):
        return "\nWrong guess:(... The number you guessed is greater than the correct number. Try again..."

    def Guess_Wrong_Lesser(self):
        return "\nWrong guess:(... The number you guessed is lesser than the correct number. Try again..."

# Creating an object.
Player1 = Game("Player1")
print(Player1.Ask_Input())

# Creating an object.
Player2 = Game("Player2")
print(Player2.Ask_Input())

def results(self1,self2):
    if self1.trials>self2.trials:
        return f"{self2.name} Wins:)"
    elif self2.trials>self1.trials:
        return f"{self1.name} Wins:)"
    else:
        return "DRAW...\n:)\n:)"

print(results(Player1,Player2))